server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ynov
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog.xml
